# Generated by Django 5.2.1 on 2025-05-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_document_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdf_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
